objectTypes:
  Perceel:
    attributes:
      identificatie:
        type: String
        identifier: true
        multiplicity: 1
      kadastraleGrootte:
        type: Integer
        multiplicity: 1
      koopsom:
        type: Integer
        multiplicity: 1
      begrenzingPerceel:
        type: Geometry
        multiplicity: 1

  LocatieKadastraalObject:
    relations:
      heeft:
        target: Perceel
        multiplicity: 1
        identifier: true
        inverseName: heeftInverse
        inverseMultiplicity: 0..*
      betreft:
        target: bag:Nummeraanduiding
        multiplicity: 1
        identifier: true
        inverseName: betreftInverse
        inverseMultiplicity: 0..*
