orchestrate:
  mapping: config/mapping/imxgeo.yaml
  sources:
    bag:
      type: file
      options:
        dataPath: data/bag

    bgt:
      type: file
      options:
        dataPath: data/bgt

    brk:
      type: file
      options:
        dataPath: data/brk
