logging:
  level:
    root: INFO
    nl.geostandaarden.imx.orchestrate: DEBUG

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.graphql.GraphQlAutoConfiguration
  graphql:
    graphiql:
      enabled: true

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

orchestrate:
  mapping: config/mapping/imxgeo.yaml
  sources:
    bag:
      type: graphql
      options:
        url: http://lookup.dhub.cs.kadaster.nl:8888/lvbag/bag-v2
        bearerToken: ${BAG_JWT_TOKEN}
        collectionSuffix: Collectie

    bgt:
      type: ogcapi
      options:
        url: https://wau.ldproxy.net/bgt
        supportsPropertySelection: true
        supportsRelProfiles: true

    brk:
      type: file
      options:
        dataPath: data/brk
