name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Build & push Docker image
        run: |
          mvn -B package spring-boot:repackage
          IMAGE_NAME=ghcr.io/imx-org/orchestrate-imxgeo:$(git rev-parse --short HEAD)
          docker build -t ${IMAGE_NAME} .
          docker push ${IMAGE_NAME}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
