lineageNameMapping:
  hasLineage: geregistreerdMet
  ObjectLineage: Registratie
  orchestratedProperties: bestaatUit
  OrchestratedProperty: GeorkestreerdGegeven
  SourceProperty: Brongegeven
  ObjectReference: Object
  subject: onderwerp
  property: kenmerk
  value: waarde
  objectKey: identificatie
  objectType: type

targetModel:
  loader: mim
  location: config/model/mimxml-imx-geo.xml

sourceModels:
  bag:
    loader: mim
    location: config/model/imbag.xml
  bgt:
    loader: mim
    location: config/model/imgeo.xml

sourceRelations:
  - sourceType: bgt:Pand
    property:
      name: gerelateerdBagPand
      target: bag:Pand
      cardinality: 0..1
      inverseName: gerelateerdBgtPand
      inverseCardinality: 0..1
      keyMapping:
        identificatie: identificatieBAGPND
#  - sourceType: bgt:Pand
#    property:
#      name: gerelateerdBagPand
#      target: bag:Pand
#      cardinality: 0..1
#      inverseName: gerelateerdBgtPand
#      inverseCardinality: 0..1
#      filterMappings:
#        - property: geometrie
#          operator:
#            type: intersects
#          sourcePath: geometrie2dGrondvlak
#
#  - sourceType: bag:Verblijfsobject
#    property:
#      name: heeftAlsHoofdadres
#      target: bag:Nummeraanduiding
#      cardinality: "1"
#      inverseName: isHoofdadresVan
#      inverseCardinality: 0..1
#
#  - sourceType: bag:Verblijfsobject
#    property:
#      name: heeftAlsNevenadres
#      target: bag:Nummeraanduiding
#      cardinality: 0..*
#      inverseName: isNevenadresVan
#      inverseCardinality: 0..1

objectTypeMappings:
  Adres:
    sourceRoot: bag:Nummeraanduiding
    propertyMappings:
      identificatie:
        pathMappings:
          path: identificatie
#      domein:
#        pathMappings:
#          path: foo
      huisnummer:
        pathMappings:
          path: huisnummer
      huisnummertoevoeging:
        pathMappings:
          path: huisnummertoevoeging
      huisletter:
        pathMappings:
          path: huisletter
      postcode:
        pathMappings:
          path: postcode
      straatnaam:
        pathMappings:
          path: ligtAan/naam
      plaatsnaam:
        pathMappings:
          path: ligtIn/naam
          andThen:
            path: ligtAan/ligtIn/naam
            ifMatch:
              type: isNull
      isHoofdadres:
        pathMappings:
          path: isHoofdadresVan/identificatie
          map:
            type: cel
            options:
              expr: 'type(result) != null_type'
      omschrijving:
        pathMappings:
          - path: ligtAan/naam
          - path: huisnummer
            map:
              type: prepend
              options:
                prefix: ' '
          - path: huisletter
            map:
              type: prepend
              options:
                prefix: ' '
          - path: huisnummertoevoeging
            map:
              type: prepend
              options:
                prefix: '-'
          - path: postcode
            map:
              type: prepend
              options:
                prefix: ', '
          - path: ligtIn/naam
            andThen: # Moet dit een or worden?
              path: ligtAan/ligtIn/naam
              ifMatch:
                type: isNull
            map:
              type: prepend
              options:
                prefix: ' '
        combiner:
          type: join
      # TODO: auto-generatie inverse mappings
      isAdresVanGebouw:
        pathMappings:
          path: isHoofdadresVan/maaktDeelUitVan/gerelateerdBgtPand

  Gebouw:
    sourceRoot: bgt:Pand
    propertyMappings:
      identificatie:
        pathMappings:
          path: identificatie
      bouwjaar:
        pathMappings:
          path: gerelateerdBagPand/oorspronkelijkBouwjaar
      bovenaanzichtgeometrie:
        pathMappings:
          path: gerelateerdBagPand/geometrie
      maaiveldgeometrie:
        pathMappings:
          path: geometrie2dGrondvlak
      heeftAlsAdres:
        pathMappings:
          - path: gerelateerdBagPand/bevat/heeftAlsHoofdadres
          - path: gerelateerdBagPand/bevat/heeftAlsNevenadres
        combiner:
          type: merge
