lineageNameMapping:
  hasLineage: geregistreerdMet
  ObjectLineage: Registratie
  orchestratedDataElements: bestaatUit
  OrchestratedDataElements: GeorkestreerdGegeven
  SourceDataElement: Brongegeven
  ObjectReference: Object
  subject: onderwerp
  property: kenmerk
  value: waarde
  objectKey: identificatie
  objectType: type
  wasDerivedFrom: isAfgeleidVan
  wasGeneratedBy: isGegenereerdDoor
  used: gebruikt

targetModel:
  loader: mim
  location: config/model/imxgeo.xml

sourceModels:
  bag:
    loader: mim
    location: config/model/imbag.xml
  bgt:
    loader: mim
    location: config/model/imgeo.xml
  brk:
    loader: yaml
    location: config/model/imkad.yaml

sourceRelations:
  - sourceType: bgt:Pand
    property:
      name: gerelateerdBagPand
      target: bag:Pand
      cardinality: 0..1
      inverseName: gerelateerdBgtPand
      inverseCardinality: 0..1
      keyMapping:
        identificatie: identificatieBAGPND
  - sourceType: brk:Perceel
    property:
      name: bevatKunstwerkdeel
      target: bgt:Kunstwerkdeel
      cardinality: 0..*
      inverseName: bevindtZichOpPerceel
      inverseCardinality: 0..*
      filterMappings:
        - property: geometrie2dOverigeConstructie
          operator: intersects
          sourcePath: begrenzingPerceel
  - sourceType: brk:Perceel
    property:
      name: bevatTunneldeel
      target: bgt:Tunneldeel
      cardinality: 0..*
      inverseName: bevindtZichOpPerceel
      inverseCardinality: 0..*
      filterMappings:
        - property: geometrie2dTunneldeel
          operator: intersects
          sourcePath: begrenzingPerceel
  - sourceType: brk:Perceel
    property:
      name: bevatPand
      target: bgt:Pand
      cardinality: 0..*
      inverseName: bevindtZichOpPerceel
      inverseCardinality: 0..*
      filterMappings:
        - property: geometrie2dGrondvlak
          operator: intersects
          sourcePath: begrenzingPerceel

objectTypeMappings:
  Adres:
    - sourceRoot: bag:Nummeraanduiding
      propertyMappings:
        identificatie:
          pathMappings:
            path: identificatie
        huisnummer:
          pathMappings:
            path: huisnummer
        huisnummertoevoeging:
          pathMappings:
            path: huisnummertoevoeging
        huisletter:
          pathMappings:
            path: huisletter
        postcode:
          pathMappings:
            path: postcode
        straatnaam:
          pathMappings:
            path: ligtAan/naam
        plaatsnaam:
          pathMappings:
            path: ligtIn/naam
            andThen:
              path: ligtAan/ligtIn/naam
              ifMatch:
                type: isNull
        isHoofdadres:
          pathMappings:
            path: isHoofdadresVan/identificatie
            map:
              type: cel
              options:
                expr: 'type(result) != null_type'
        omschrijving:
          pathMappings:
            - path: ligtAan/naam
            - path: huisnummer
              map:
                type: prepend
                options:
                  prefix: ' '
            - path: huisletter
              map:
                type: prepend
                options:
                  prefix: ' '
            - path: huisnummertoevoeging
              map:
                type: prepend
                options:
                  prefix: '-'
            - path: postcode
              map:
                type: prepend
                options:
                  prefix: ', '
            - path: ligtIn/naam
              andThen: # Moet dit een or worden?
                path: ligtAan/ligtIn/naam
                ifMatch:
                  type: isNull
              map:
                type: prepend
                options:
                  prefix: ' '
          combiner:
            type: join
        isAdresVanGebouw:
          pathMappings:
            path: isHoofdadresVan/maaktDeelUitVan/gerelateerdBgtPand

  Bouwwerk:
    - sourceRoot: bgt:Kunstwerkdeel
      propertyMappings:
        identificatie:
          pathMappings:
            path: identificatie
        maaiveldgeometrie:
          pathMappings:
            path: geometrie2dOverigeConstructie
    - sourceRoot: bgt:Tunneldeel
      propertyMappings:
        identificatie:
          pathMappings:
            path: identificatie
        maaiveldgeometrie:
          pathMappings:
            path: geometrie2dTunneldeel

  Gebouw:
    - sourceRoot: bgt:Pand
      propertyMappings:
        identificatie:
          pathMappings:
            path: identificatie
        bouwjaar:
          pathMappings:
            path: gerelateerdBagPand/oorspronkelijkBouwjaar
        bovenaanzichtgeometrie:
          pathMappings:
            path: gerelateerdBagPand/geometrie
        maaiveldgeometrie:
          pathMappings:
            path: geometrie2dGrondvlak
        heeftAlsAdres:
          pathMappings:
            - path: gerelateerdBagPand/bevat/heeftAlsHoofdadres
            - path: gerelateerdBagPand/bevat/heeftAlsNevenadres
          combiner:
            type: merge

  Perceel:
    - sourceRoot: brk:Perceel
      propertyMappings:
        identificatie:
          pathMappings:
            path: identificatie
        laatsteKoopsom:
          pathMappings:
            path: koopsom
        oppervlak:
          pathMappings:
            path: kadastraleGrootte
        begrenzing:
          pathMappings:
            path: begrenzingPerceel
        bevatGebouw:
          pathMappings:
            path: bevatPand
        bevatBouwwerk:
          pathMappings:
            - path: bevatKunstwerkdeel
            - path: bevatTunneldeel
          combiner:
            type: merge
